---
# tasks file for ic_it.deploy_vmware_log_insight_agent
- name: copy the debian package locally
  copy:
    src: vmware-log-insight-agent_8.10.2-21113573_all_128.178.131.4.deb
    dest: /tmp/vmware-log-insight-agent_8.10.2-21113573_all_128.178.131.4.deb

- name: install the vmware-log-insight-agent package
  apt:
    deb: /tmp/vmware-log-insight-agent_8.10.2-21113573_all_128.178.131.4.deb
    state: present
